(() => {
  "use strict";
  const baseUrl = new URL("./", document.currentScript.src);
  const state = {items:[],filtered:[],map:null,layer:null,markers:new Map(),category:"all",search:"",selectedId:null,favorites:new Set(),votes:{}};
  const cats={all:["Tots","\u2726"],"bike-base":["Bike Base","\ud83c\udfe1"],mirador:["Mirador","\ud83d\udcf8"],monument:["Monument","\ud83c\udfdb\ufe0f"],platja:["Platja","\ud83c\udfd6\ufe0f"],estacio:["Estaci\u00f3","\ud83d\ude89"],"tram-bonic":["Tram bonic","\ud83c\udf3f"]};
  const info=c=>cats[c]||[c,"\ud83d\udccd"];
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
  const votes=i=>Number(i.votes||0)+Number(state.votes[i.id]||0);
  const rating=i=>Number(i.rating||0)?Number(i.rating).toFixed(1).replace(".",","):"\u2014";

  function loadLocal(){try{state.favorites=new Set(JSON.parse(localStorage.getItem("bicipark.highlights.favorites")||"[]"));state.votes=JSON.parse(localStorage.getItem("bicipark.highlights.votes")||"{}")}catch(e){console.warn(e)}}
  function saveLocal(){localStorage.setItem("bicipark.highlights.favorites",JSON.stringify([...state.favorites]));localStorage.setItem("bicipark.highlights.votes",JSON.stringify(state.votes))}
  async function json(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);return r.json()}
  const num=v=>Number.isFinite(Number(v))?Number(v):null;

  function baseToItem(b){const l=b.location||{};const lat=num(b.lat)??num(b.latitude)??num(l.lat)??num(l.latitude);const lng=num(b.lng)??num(b.lon)??num(b.longitude)??num(l.lng)??num(l.lon)??num(l.longitude);if(lat==null||lng==null)return null;const id=String(b.id||b.slug||b.code||b.name||("base-"+lat+"-"+lng));const score=num(b.bikeFriendlyIndex??b.bikeFriendlyScore??b.score);return{id:"bike-base-"+id,name:b.name||b.title||"Bike Base",category:"bike-base",lat,lng,region:b.region||l.region||b.locality||l.locality||"",description:b.description||"Bike Base BiciPark per descobrir el territori en bicicleta.",rating:score!=null?Math.min(5,Math.max(1,score/20)):4.5,votes:0,sourceType:"bike-base"}}
  async function loadBases(){try{const raw=await json(new URL("../../bike-bases/data/bike-bases.json",baseUrl).href);const list=Array.isArray(raw)?raw:(raw.bases||raw.items||raw.data||raw.results||[]);return Array.isArray(list)?list.map(baseToItem).filter(Boolean):[]}catch(e){console.info("[Highlights] Bike Bases optional",e.message);return[]}}
  async function load(){const local=await json(new URL("./data/highlights.json",baseUrl).href);const bases=await loadBases();const map=new Map();[...local,...bases].forEach(i=>map.set(i.id,i));state.items=[...map.values()];state.filtered=[...state.items]}

  function icon(item){const [label,emoji]=info(item.category);return L.divIcon({className:"",html:'<div class="hl-marker"><span>'+emoji+'</span></div>',iconSize:[34,34],iconAnchor:[17,33],popupAnchor:[0,-32]})}
  function popup(item){const [label,emoji]=info(item.category);return '<div class="hl-popup"><div class="hl-popup-kicker">'+emoji+' '+esc(label)+'</div><h3>'+esc(item.name)+'</h3><p>'+esc(item.description||"")+'</p><div class="hl-meta"><span>\u2b50 '+rating(item)+'</span><span>\ud83d\udc4d '+votes(item)+'</span></div><div class="hl-popup-actions"><button data-act="rec" data-id="'+esc(item.id)+'">Recomanar +1</button><button data-act="route" data-id="'+esc(item.id)+'">Afegir a ruta</button></div></div>'}

  function initMap(){state.map=L.map("highlightsMap").setView([41.82,2.35],8);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(state.map);state.layer=L.layerGroup().addTo(state.map);state.map.on("popupopen",wirePopup)}
  function wirePopup(){document.querySelectorAll("[data-act]").forEach(b=>{if(b.dataset.bound)return;b.dataset.bound="1";b.addEventListener("click",()=>{const item=state.items.find(i=>i.id===b.dataset.id);if(!item)return;if(b.dataset.act==="rec"){state.votes[item.id]=Number(state.votes[item.id]||0)+1;saveLocal();render();window.BiciParkCore?.emit("highlights:recommended",item)}else{window.BiciParkCore?.emit("highlights:add-to-route",item);alert("Highlight preparat per al futur Route Planner: "+item.name)}})})}

  function categories(){const counts={};state.items.forEach(i=>counts[i.category]=(counts[i.category]||0)+1);const keys=["all","bike-base","mirador","monument","platja","estacio","tram-bonic"];const root=document.getElementById("highlightCategories");root.innerHTML=keys.filter(k=>k==="all"||(counts[k]||0)>0).map(k=>{const [label,emoji]=info(k);const count=k==="all"?state.items.length:(counts[k]||0);return '<button class="hl-category '+(state.category===k?"is-active":"")+'" data-cat="'+k+'">'+emoji+' '+esc(label)+' ('+count+')</button>'}).join("");root.querySelectorAll("[data-cat]").forEach(b=>b.addEventListener("click",()=>{state.category=b.dataset.cat;filter()}))}
  function card(i){const [label,emoji]=info(i.category);const fav=state.favorites.has(i.id);return '<article class="hl-card '+(state.selectedId===i.id?"is-selected":"")+'" data-id="'+esc(i.id)+'"><div class="hl-card-top"><div><h3>'+esc(i.name)+'</h3><span class="hl-cat">'+emoji+' '+esc(label)+'</span></div><button class="hl-fav '+(fav?"is-active":"")+'" data-fav="'+esc(i.id)+'">'+(fav?"\u2605":"\u2606")+'</button></div><p>'+esc(i.description||"")+'</p><div class="hl-meta"><span>\ud83d\udccd '+esc(i.region||"")+'</span><span>\u2b50 '+rating(i)+'</span><span>\ud83d\udc4d '+votes(i)+'</span></div></article>'}
  function list(){const root=document.getElementById("highlightList");root.innerHTML=state.filtered.length?state.filtered.map(card).join(""):'<div class="hl-note">No hi ha Highlights que coincideixin amb aquests filtres.</div>';root.querySelectorAll(".hl-card").forEach(c=>c.addEventListener("click",e=>{if(e.target.closest("[data-fav]"))return;select(c.dataset.id)}));root.querySelectorAll("[data-fav]").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();const id=b.dataset.fav;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);saveLocal();list()}))}
  function markers(){state.layer.clearLayers();state.markers.clear();state.filtered.forEach(i=>{const m=L.marker([i.lat,i.lng],{icon:icon(i)}).bindPopup(popup(i),{maxWidth:300});m.on("click",()=>{state.selectedId=i.id;list()});m.addTo(state.layer);state.markers.set(i.id,m)})}
  function render(){categories();list();markers();document.getElementById("highlightCount").textContent=state.filtered.length;document.getElementById("listCount").textContent=state.filtered.length+" resultats"}
  function filter(){const q=state.search.trim().toLowerCase();state.filtered=state.items.filter(i=>(state.category==="all"||i.category===state.category)&&(!q||(i.name+" "+(i.description||"")+" "+(i.region||"")).toLowerCase().includes(q)));render()}
  function select(id){const i=state.items.find(x=>x.id===id);if(!i)return;state.selectedId=id;list();state.map.flyTo([i.lat,i.lng],Math.max(state.map.getZoom(),14),{duration:.7});setTimeout(()=>state.markers.get(id)?.openPopup(),500)}
  function fit(){if(!state.filtered.length)return;state.map.fitBounds(L.latLngBounds(state.filtered.map(i=>[i.lat,i.lng])),{padding:[35,35],maxZoom:13})}
  function near(){if(!navigator.geolocation){alert("Aquest navegador no permet geolocalitzacio.");return}navigator.geolocation.getCurrentPosition(p=>{const ll=[p.coords.latitude,p.coords.longitude];state.map.flyTo(ll,13);L.circleMarker(ll,{radius:8,color:"#fff",weight:3,fillColor:"#2877e8",fillOpacity:1}).addTo(state.map).bindPopup("La teva ubicacio").openPopup()},()=>alert("No s'ha pogut obtenir la ubicacio."),{enableHighAccuracy:true,timeout:10000})}

  async function boot(){loadLocal();initMap();document.getElementById("highlightSearch").addEventListener("input",e=>{state.search=e.target.value;filter()});document.getElementById("nearMeButton").addEventListener("click",near);document.getElementById("fitButton").addEventListener("click",fit);try{await load();filter();fit();window.BiciParkCore?.registerModule({id:"highlights",version:"1.0.0",api:{getAll:()=>[...state.items],getFiltered:()=>[...state.filtered],select}});window.BiciParkCore?.emit("highlights:ready",{count:state.items.length})}catch(e){console.error(e);document.getElementById("highlightList").innerHTML='<div class="hl-note">No s\'han pogut carregar els Highlights.</div>'}}
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot):boot();
})();